<<<<<<< Updated upstream
from person import Person, Tourist, Employee
from logement import Logement, Hotel, Auberge

name = input("Enter your name :")
firstname = input("Enter your firstname : ")
contact = input("Enter your contact : ")

p = Person(name, firstname, contact)
print(p.display())

t = Tourist(name, firstname, contact)
preference = input("Enter your preference: ")
t.add_preference(preference)

while True:
  choice = input("Do you want to add more preferences? (yes/no:) ")
  if choice =="no"
    break
  preference = input("Enter  your preference: ")
  t.add_preference(preference)
print(t.display())
print(t.get_preferences())

post = input("Enter your post: ")
salary = input("Enter your salary: ")
e = Employee(name, firstname, contact, post, salary)
print(e.display())

name = input("Enter hotel's name : ")
localisation = input("Enter the localisation : ")
cost = input("Enter the cost : ")
stars = input("Enter the number of stars : ")
services = input("Enter the services : ")
services_list = []
for service in services.split(","):
  services_list.append(service.strip())
cost = int(cost)
stars = int(stars)
h = Hotel(name, localisation, cost, stars, services_list)
h.display()

name = input("Enter auberge's name : ")
localisation = input("Enter the localisation : ")
cost = input("Enter the cost : ")
type_dormitory = input("Enter the type of dormitory : ")
cost = int(cost)
a = Auberge(name, localisation, cost, type_dormitory)
a.display()
=======
from logement import Hotel, Auberge
hotel1 = Hotel("Hotel Splendide", "OUAGADOUGOU", 50000, 4, ["Wi-Fi", "Piscine"])
auberge1 = Auberge("Auberge Bilimpo", "Fada N'Gourma", 20000, "Mixed Dormitory")
hotel2 = Hotel("Hotel de la Paix", "Lagos", 30000, 3, ["Wi-Fi", "Restaurant"])
auberge2 = Auberge("Auberge du 11 Decembre", "Fada N'Gourma", 15000, "Female Dormitory")
hotel3 = Hotel("Laico hotel", "OUAGADOUGOU", 40000, 5, ["Wi-Fi", "Piscine", "Spa"])
auberge3 = Auberge("Auberge song taaba", "OUAGADOUGOU", 25000, "Male Dormitory")
hotel4 = Hotel("Hotel silmende", "OUAGADOUGOU", 35000, 4, ["Wi-Fi", "Piscine", "Restaurant"])
auberge4 = Auberge("Auberge du LA VIDA LOCA", "OUAGADOUGOU", 18000, "Female Dormitory")
hotel5 = Hotel("Bravia Hotel", "OUAGADOUGOU", 45000, 5, ["Wi-Fi", "Piscine", "Spa", "Restaurant"])
hotel6 = Hotel("Lancaster ouaga 2000", "OUAGADOUGOU", 55000, 5, ["Wi-Fi", "Piscine", "Spa", "Restaurant"])
hotel7 = Hotel("Hotel kavana", "OUAGADOUGOU", 40000, 4, ["Wi-Fi", "Piscine"])
hotel8 = Hotel("Bravia Hotel", "OUAGADOUGOU", 45000, 5, ["Wi-Fi", "Piscine", "Spa", "Restaurant"])
hotel9 = Hotel("hotel sissiman", "Bobo-Dioulasso", 35000, 4, ["Wi-Fi", "Piscine", "Restaurant"])
hotel10 = Hotel("villa Bobo", "Bobo-Dioulasso", 30000, 3, ["Wi-Fi", "Piscine"])
hotel11 = Hotel("pacific hotel", "Bobo-Dioulasso", 40000, 4, ["Wi-Fi", "Piscine", "Restaurant"])
hotel12 = Hotel("cascades Palace", "Banfora", 45000, 3, ["Wi-Fi", "Piscine", "Spa", "Restaurant"])
hotel13 = Hotel("Hotel canne a sucre", "Banfora ", 30000, 3, ["Wi-Fi", "Piscine"])
hotel14 = Hotel("Hotel du lac", "Banfora", 35000, 4, ["Wi-Fi", "Piscine", "Restaurant"])
hotel15 = Hotel("campement touristique", "Dedougou", 25000, 2, ["Wi-Fi"])
hotel16 = Hotel("Hotel Tieba", "Tenkodogo", 20000, 2, ["Wi-Fi"])
hotel17 = Hotel("Hotel djamou", "Tenkodogo", 30000, 3, ["Wi-Fi", "Piscine"])
hotel18 = Hotel("Hotel du kaziende", "Kaya", 35000, 4, ["Wi-Fi", "Piscine", "Restaurant"])
hotel19 = Hotel("pacific hotel kaya", "Kaya", 40000, 4, ["Wi-Fi", "Piscine", "Restaurant"])
hotel20 = Hotel("Hotel la grace divine", "Kaya", 45000, 5, ["Wi-Fi", "Piscine", "Spa", "Restaurant"])
hotel1.display()
print("\n")
hotel2.display()
print("\n")
hotel3.display()
print("\n")
hotel4.display()
print("\n")
hotel5.display()
print("\n")
hotel3.display()
print("\n")
auberge3.display()
print("\n")
hotel4.display()
print("\n")
auberge4.display()
print("\n")
hotel5.display()
print("\n")
hotel6.display()
print("\n")
hotel7.display()
print("\n")
hotel8.display()
print("\n")
hotel9.display()
print("\n")
hotel10.display()
print("\n")
hotel11.display()
print("\n")
hotel12.display()
print("\n")
hotel13.display()
print("\n")
hotel14.display()
print("\n")
hotel15.display()
print("\n")
hotel16.display()
print("\n")
hotel17.display()
print("\n")
hotel18.display()
print("\n")
hotel19.display()
print("\n")
hotel20.display()
>>>>>>> Stashed changes
